services:
  caddy:
    image: "caddy:2-alpine"
    ports:
      - "3000:80"
    depends_on:
      - web
      - api
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"

  web:
    image: "ghcr.io/dhoinka/clock-in/web"

  api:
    image: "ghcr.io/dhoinka/clock-in/api"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-local-postgres-password-change-before-deployment}"

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-local-postgres-password-change-before-deployment}"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
